#!/bin/bash

# Make sure JAR is up to date before running jar
# and that gradle do not consume standard in stream
echo "" | ./gradlew inScala:assemble > /dev/null && \
scala -classpath inScala/build/libs/inScala.jar $1

